server:
  port: 8080
  servlet:
    context-path: /smarthomesys
#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smarthome?serverTimezone=UTC&characterEncoding=UTF8
    username: root
    password: 906913
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  mapper-locations: classpath*:com/qianfeng/smarthome/mapper/xml/*.xml
  type-aliases-package: com.qianfeng.smarthome.entity



